---
title: "R Notebook"
output: html_notebook
---
```{r}
library(tidyverse)
library(NbClust)
library(rpart)
library(rpart.plot)
```


```{r input_data}
df <- read_csv("../data/output/segmented-Mall_Customers.csv") 
```

for each group create a dataset that has a column indicating if an observation
is a member the resepective group. this indicator column will will be the outcome
that the decision tree will aim to predict.
```{r}
# 0. create a function to identify if observation is a member of the specified group
group_indicator = function(base_group, categories = df$segments){
  indicator <- categories == base_group 
  
  bind_cols(df, indicator = indicator) %>%
  select(-segments)
}

# 1. store each modified dataset as an item in a list
cart_df = purrr::map(unique(df$segments), group_indicator)
# 2. name each dataset
names(cart_df) = paste0("group_", unique(df$segments))
names(cart_df)
```

# Decision Trees
```{r group_1}
set.seed(19890522)

tree <- rpart(indicator~., 
              data=cart_df$group_1, 
              method = "class")

# Prune back the tree to avoid overfitting the data
printcp(tree)
bestcp <- tree$cptable[which.min(tree$cptable[,"xerror"]),"CP"]
tree.pruned <- prune(tree, cp = bestcp)

# Look at confusion matrix
conf.matrix <- table(cart_df$group_1$indicator,
                     predict(tree.pruned, type = "class"))
rownames(conf.matrix) <- paste("Actual", rownames(conf.matrix), sep = ":")
colnames(conf.matrix) <- paste("Pred", colnames(conf.matrix), sep = ":")
print(conf.matrix)

# Decision tree
prp(tree.pruned, faclen = 0, cex = 0.8, extra = 1)
```

```{r group_2}
set.seed(19890522)
# model containing the essential nutrients & food category
tree <- rpart(indicator~., 
              data=cart_df$group_2, 
              method = "class")

# Prune back the tree to avoid overfitting the data
printcp(tree)
bestcp <- tree$cptable[which.min(tree$cptable[,"xerror"]),"CP"]
tree.pruned <- prune(tree, cp = bestcp)

# Look at confusion matrix
conf.matrix <- table(cart_df$group_1$indicator,
                     predict(tree.pruned, type = "class"))
rownames(conf.matrix) <- paste("Actual", rownames(conf.matrix), sep = ":")
colnames(conf.matrix) <- paste("Pred", colnames(conf.matrix), sep = ":")
print(conf.matrix)

# Decision tree
prp(tree.pruned, faclen = 0, cex = 0.8, extra = 1)
```

```{r group_3}
set.seed(19890522)
# model containing the essential nutrients & food category
tree <- rpart(indicator~., 
              data=cart_df$group_3, 
              method = "class")

# Prune back the tree to avoid overfitting the data
printcp(tree)
bestcp <- tree$cptable[which.min(tree$cptable[,"xerror"]),"CP"]
tree.pruned <- prune(tree, cp = bestcp)

# Look at confusion matrix
conf.matrix <- table(cart_df$group_1$indicator,
                     predict(tree.pruned, type = "class"))
rownames(conf.matrix) <- paste("Actual", rownames(conf.matrix), sep = ":")
colnames(conf.matrix) <- paste("Pred", colnames(conf.matrix), sep = ":")
print(conf.matrix)

# Decision tree
prp(tree.pruned, faclen = 0, cex = 0.8, extra = 1)
```

```{r group_4}
set.seed(19890522)
# model containing the essential nutrients & food category
tree <- rpart(indicator~., 
              data=cart_df$group_4, 
              method = "class")


# Prune back the tree to avoid overfitting the data
printcp(tree)
bestcp <- tree$cptable[which.min(tree$cptable[,"xerror"]),"CP"]
tree.pruned <- prune(tree, cp = bestcp)

# Look at confusion matrix
conf.matrix <- table(cart_df$group_1$indicator,
                     predict(tree.pruned, type = "class"))
rownames(conf.matrix) <- paste("Actual", rownames(conf.matrix), sep = ":")
colnames(conf.matrix) <- paste("Pred", colnames(conf.matrix), sep = ":")
print(conf.matrix)

# Decision tree
prp(tree.pruned, faclen = 0, cex = 0.8, extra = 1)
```

```{r group_5}
set.seed(19890522)
# model containing the essential nutrients & food category
tree <- rpart(indicator~., 
              data=cart_df$group_5, 
              method = "class")


# Prune back the tree to avoid overfitting the data
printcp(tree)
bestcp <- tree$cptable[which.min(tree$cptable[,"xerror"]),"CP"]
tree.pruned <- prune(tree, cp = bestcp)

# Look at confusion matrix
conf.matrix <- table(cart_df$group_1$indicator,
                     predict(tree.pruned, type = "class"))
rownames(conf.matrix) <- paste("Actual", rownames(conf.matrix), sep = ":")
colnames(conf.matrix) <- paste("Pred", colnames(conf.matrix), sep = ":")
print(conf.matrix)

# Decision tree
prp(tree.pruned, faclen = 0, cex = 0.8, extra = 1)
```

```{r group_6}
set.seed(19890522)
# model containing the essential nutrients & food category
tree <- rpart(indicator~., 
              data=cart_df$group_6, 
              method = "class")


# Prune back the tree to avoid overfitting the data
printcp(tree)
bestcp <- tree$cptable[which.min(tree$cptable[,"xerror"]),"CP"]
tree.pruned <- prune(tree, cp = bestcp)

# Look at confusion matrix
conf.matrix <- table(cart_df$group_1$indicator,
                     predict(tree.pruned, type = "class"))
rownames(conf.matrix) <- paste("Actual", rownames(conf.matrix), sep = ":")
colnames(conf.matrix) <- paste("Pred", colnames(conf.matrix), sep = ":")
print(conf.matrix)

# Decision tree
prp(tree.pruned, faclen = 0, cex = 0.8, extra = 1)
```
```{r}
pairs(df[,1:4], col=df$segments)
```

```{r}
ggplot(df, aes(`Annual Income (k$)`, `Spending Score (1-100)`, color = as.factor(segments))) +
  geom_point() +
  theme_minimal() + 
  scale_x_continuous(breaks = seq(0, max(df$`Annual Income (k$)`), by = 20)) + 
  scale_y_continuous(breaks = seq(0, max(df$`Spending Score (1-100)`), by = 20))
```

```{r}
ggplot(df, aes(Age, `Spending Score (1-100)`, color = as.factor(segments))) +
  geom_point() +
  theme_minimal()
```

```{r}
ggplot(df, aes(`Annual Income (k$)`, Age, color = as.factor(segments))) +
  geom_point() +
  theme_minimal()
```

```{r}
table(df$Age, df$segments)
```

```{r}
table(df$`Annual Income (k$)`, df$segments)
```

```{r}
table(df$`Spending Score (1-100)`, df$segments)
```

```{r}
table(df$female, df$segments)
```

